### ISSUE TITLE
Overfull and underfull \hbox on Approval page

### ISSUE THREAD

**Issue by kevin-j-morse** [rchurchley/thesis-template#12] opened 2015-03-31 22:52 UTC
Hi Ross,

I just compiled the template using `pdfTeX, Version 3.1415926-2.5-1.40.14 (MiKTeX 2.9) (preloaded format=pdflatex 2013.10.25)` on Windows 7 64 bit and received the following Badbox errors from the Approval page

> Overfull \hbox (4.86665pt too wide) in paragraph at lines 81--81
> Overfull \hbox (4.86665pt too wide) in paragraph at lines 81--81
> Overfull \hbox (4.86665pt too wide) in paragraph at lines 81--81
> Overfull \hbox (7.29999pt too wide) in paragraph at lines 81--81
> Underfull \hbox (badness 10000) in paragraph at lines 81--81
> Overfull \hbox (4.86665pt too wide) in paragraph at lines 81--81
> Underfull \hbox (badness 10000) in paragraph at lines 81--81

If this was a page in the thesis and only a single badbox error I would ignore it but there are a few reasons I'm filing this issue.

1. I don't think there should be this many errors on the second page of the document
2. If users are using a program which shows warnings they won't actual notice any warnings from anywhere else in the document because there are so many here. If they suppress them then they'd miss potentially useful messages.
3. I actually agree with pdfTeX about the underfull boxes. The top half of the page is very dense and cramped while the bottom has a huge amount of white space. 

I compiled in Draft mode and have attached a PDF with the overfull boxes marked and my guess for where one of the underfull boxes is.

![approval page from template](https://cloud.githubusercontent.com/assets/4412177/6930936/e952df64-d7bc-11e4-979b-b618837c3989.png)

Comparing this page to the approval page from the other template which I think makes a better use of space.

![approval page from my undergrad thesis](https://cloud.githubusercontent.com/assets/4412177/6930884/608a4be0-d7bc-11e4-9b5f-55f35412660b.png)

**Comment by kevin-j-morse** [comment] 2015-03-31 23:01
A follow up comment I just noticed is that Name, Degree, and Title are actually a few points further to the left than the Chair.

**Comment by rchurchley** [comment] 2015-03-31 23:14
Good catch on the overfill errors, which was caused by whitespace between fixed-width elements whose widths sum to \linewidth. To prevent this from happening in the future, 8cb9346 adjusts the width of the right-hand "column" to provide some buffer space, which has the happy side effect of aligning that column with the signature lines. The chair being a few points to the left is, I believe, the result of an errant (and invisible) \hrulefill at the end of that line, which I've now removed.

**Comment by kevin-j-morse** [comment] 2015-03-31 23:32
Thanks!

Looks much better.

One more issue that I noticed once I added my thesis title is that committee is being hyphenated to commit-tee which isn't too attractive...

Is there any reason the chair is at the top? From a semantic point of view it's kind of weird for them to be grouped with the Author's Name, Degree, and the Thesis Title and from an aesthetic point of view it would fix the hyphenation issue and use up some more space.

Could they not just be listed like all the other committee members but have no signature line beside there name?

![examining committee hyphen](https://cloud.githubusercontent.com/assets/4412177/6931499/c6a74710-d7c2-11e4-9746-eb638b9fbae3.png)

**Comment by rchurchley** [comment] 2015-03-31 23:42
(To address your second issue) The issue with the underfilled box between the committee and the date is partly by design. The library has a hard requirement that the committee fits on one page, and I've heard from at least one PhD student have trouble fitting his seven-person committee onto the page using the old template.

I agree with you that with small committees, however, it does look pretty ugly. How do you like it if we put flexible spaces between committee members?

![Small committee](https://cloud.githubusercontent.com/assets/1131743/6931634/6706f894-d7c4-11e4-90cd-8188d5fcd3cb.png)

![Large committee](https://cloud.githubusercontent.com/assets/1131743/6931677/d38d4db0-d7c4-11e4-980f-8117c4840c32.png)

**Comment by kevin-j-morse** [comment] 2015-03-31 23:46
I think that goes a long way in addressing the spacing issues but I think it would also be helpful to move the Chair down with the rest of the committee.

**Comment by rchurchley** [comment] 2015-03-31 23:49
The chair is at the top as per library recommendations; the thesis adviser suggested at the last meeting to make the LaTeX template approval page closer to the Word one if possible. If I were to design it from scratch, I'd definitely have the chair in the same format as the rest of the committee, but I would want to get further input from the library before changing it.

**Comment by kevin-j-morse** [comment] 2015-04-01 00:14
Ahhhh... Stupid Word template...

I'm annoyed I didn't catch that at the meeting or I would've made a fuss. It's hard to see these things when you're not actively working on the template. No worries if that can't be changed. I'll just do it on my copy.

**Comment by rchurchley** [comment] 2015-04-01 00:26
The spacing on the examining committee should now be fixed as of a2b3b18. I'll close this issue, and perhaps we should resolve to ask the library about placement of the chair.

**Closed by rchurchley** 2015-04-01 00:26 UTC
