### ISSUE TITLE
Error when compiling unmodified template

### ISSUE THREAD

**Issue by amcpherson** [rchurchley/thesis-template#14] opened 2015-04-23 16:38 UTC
Using pdflatex:
```
pdflatex template.tex
```

I get the following error.

```
! Undefined control sequence.
<argument> ... \newcommand *{\Appendixautorefname
                                                  }{Appendix}
l.65 \begin{document}
```

**Comment by rchurchley** [comment] 2015-04-23 16:51
How embarrassing! This regression was caused by me missing the second extra `{}` at the end of `pretocmd` on the previous line, and has been fixed in ce602f.

**Closed by rchurchley** 2015-04-23 16:51 UTC
Labels: bug
